### ISSUE TITLE
npm run build:watch doesn't watch scss files

### ISSUE THREAD

**Issue by SebConejo** [case-app/angular-library#1]
I faced a problem: on `@angular/cli@10.2.0` command `npm run build:watch` builds app successfully but doesn't watch all scss files. Only scss component files are tracked.

**Comment by brunobuddy** [comment]
Building the library at each change is not an optimized worfklow.

Instead I created a showcase app that can use directly the lib components without building the library. It reloads on every file change, produces source maps and is faster.

The only drawback is that we have to replicate parts of the CASE app pages to work on. 

![Screenshot from 2021-10-03 15-25-22](https://user-images.githubusercontent.com/6626184/135755903-7ebb98c3-9c58-4761-9e6c-8da45d9bc87d.png)
