### ISSUE TITLE
dropdown in tables : display a dropdown dynamically using js

### ISSUE THREAD

**Issue by SebConejo** [case-app/angular-library#6]
![Capture d’écran 2021-08-24 à 18 01 00](https://user-images.githubusercontent.com/11723962/130650513-7b1e0ee6-7d48-4086-bfa1-691b849d24db.png)

Currently, the dropdown appears within the table. But with CSS, we can't give an highest z-index  with an overflow to the table. another css rule which contradicts this one must be kept.

So the solution could be to display it outside the table. So we could apply a dynamic position with a js function. A bit like a modal for example.

**Comment by brunobuddy** [comment]
@SebConejo do you have an alternative for that ? The process of having a component that appears on top level in the DOM is feasible but long to code, the positioning of the element can be tricky too

**Comment by SebConejo** [comment]
We talk about his issue here: https://github.com/case-app/case/issues/46
