### ISSUE TITLE
Some components are missing

### ISSUE THREAD

**Issue by SebConejo** [case-app/angular-library#9]
- [ ] checkbox block
- [ ] Radio buttons
- [ ] tabs
- [ ] menu lateral (css only)
- [ ] Modals

**Comment by brunobuddy** [comment]
@SebConejo please provide more information 

 checkbox block : We have a checkbox input component. Do you mean something else ?
 Radio buttons: We have a radio input component. Is it not working ?
 menu lateral (css only) : The side menu is located on elements/navigation. 

For tabs and modals, we do not have a standard yet. Do you want to add it in the roadmap ?

Closing this issue as it is related to several topics. Please open one issue per element if needed.
